"""
Provenance logging.

Every synthetic record generated by this project (skeleton, document, or
memo) should log an entry here. This is the auditable trail that lets us
say, with evidence, that nothing in the synthetic dataset traces back to
real insurer data -- every record's origin is either "randomly sampled
from a public-distribution seed" or "LLM-generated from a synthetic
skeleton", both logged with enough detail to reproduce.

Append-only JSONL. One JSON object per line.
"""

from __future__ import annotations

import json
import platform
import threading
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

_lock = threading.Lock()

ProvenanceStage = Literal[
    "corpus_ingest",
    "characteristic_profiling",
    "skeleton_sampling",
    "stage_a_document_gen",
    "stage_b_memo_gen",
    "noise_injection",
    "classification_train",
    "classification_vit_train",
    "classification_train_random_forest",
    "extraction_train",
    "eval_comparison",
    "sample_corpus_seed",
    "sample_corpus_import",
    "sample_corpus_export",
]


@dataclass
class ProvenanceRecord:
    record_id: str
    stage: ProvenanceStage
    source: str
    prompt_version: str
    model: str | None
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    extra: dict[str, Any] = field(default_factory=dict)
    host: str = field(default_factory=platform.node)

    def to_json_line(self) -> str:
        return json.dumps(asdict(self), ensure_ascii=False)


def log_provenance(log_path: Path, record: ProvenanceRecord) -> None:
    """Thread-safe append of a single provenance record."""
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with _lock:
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(record.to_json_line() + "\n")


def read_provenance(log_path: Path) -> list[dict[str, Any]]:
    if not log_path.exists():
        return []
    records = []
    with open(log_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


class ProvenanceLogger:
    """
    Lightweight dict stamper used by the frontier vs. local eval harness.

    Stamps ``run_id`` / ``provenance_tag`` / ``timestamp`` onto each record and
    optionally mirrors a compact entry into the project provenance JSONL.
    """

    def __init__(
        self,
        run_id: str,
        tag: str,
        log_path: Path | None = None,
        mirror_to_log: bool = True,
    ):
        self.run_id = run_id
        self.tag = tag
        self.log_path = log_path
        self.mirror_to_log = mirror_to_log

    def log(self, record: dict[str, Any]) -> None:
        record.setdefault("run_id", self.run_id)
        record.setdefault("provenance_tag", self.tag)
        record.setdefault("timestamp", datetime.now(timezone.utc).isoformat())

        if self.mirror_to_log and self.log_path is not None:
            example_id = str(record.get("example_id") or record.get("record_id") or "unknown")
            mirrored = ProvenanceRecord(
                record_id=f"eval::{self.run_id}::{example_id}",
                stage="eval_comparison",
                source=self.tag,
                prompt_version=str(record.get("prompt_version") or "eval_harness_v1"),
                model=str(record.get("model_id")) if record.get("model_id") else None,
                extra={
                    "task": record.get("task"),
                    "backend": record.get("backend"),
                    "cost_usd": record.get("cost_usd"),
                    "latency_seconds": record.get("latency_seconds"),
                    "error": record.get("error"),
                },
            )
            log_provenance(self.log_path, mirrored)
